### PR TITLE
Add vi functionality

### PR DESCRIPTION
**Pull request by karloluiten**
Add a vi command to open the file with vi, for easy editing.

### CODE REVIEW

**Comment by craigmaloney** [comment]
How is this different from the edit command that's already present? Or is this an override of the $EDITOR environment variable?

**Comment by karloluiten** [comment]
If I do  `t -h` I don't get an edit command? I have never seen an edit command...

**Comment by craigmaloney** [comment]
It's a separate plugin (apologies, as I thought this was standard).

https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#edit-open-in-text-editor

**Comment by jucor** [comment]
Thanks @craigmaloney for pointing to `t edit`, it's exactly what I needed!

**Comment by craigmaloney** [comment]
Glad it's working. :)

**Comment by karloluiten** [comment]
Well this is here already. Let's close.

**Pull request closed without merging**
